apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-app
  labels:
    app: discovery-service-app
spec:
  selector:
    matchLabels:
      app: discovery-service-app
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: discovery-service-app
    spec:
      containers:
        - name: discovery-service-app
          image: discovery-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
